
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Mar 22 17:14:41 CET 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 11;
  public static final int MENOS = 5;
  public static final int AND = 16;
  public static final int IGUALIGUAL = 24;
  public static final int MENOR = 20;
  public static final int ELSE = 26;
  public static final int INT = 29;
  public static final int MENORIGUAL = 22;
  public static final int OR = 17;
  public static final int IGUAL = 8;
  public static final int WHILE = 27;
  public static final int NOT = 18;
  public static final int RETURN = 33;
  public static final int IDEN = 2;
  public static final int TRUE = 31;
  public static final int CCIERRE = 13;
  public static final int IF = 25;
  public static final int POR = 6;
  public static final int CAP = 12;
  public static final int COMA = 9;
  public static final int DISTINTO = 23;
  public static final int MAYOR = 19;
  public static final int EOF = 0;
  public static final int DIV = 7;
  public static final int MAYORIGUAL = 21;
  public static final int PAP = 10;
  public static final int LLCIERRE = 15;
  public static final int FALSE = 32;
  public static final int error = 1;
  public static final int LLAP = 14;
  public static final int BOOL = 30;
  public static final int PUNTOCOMA = 28;
  public static final int ENT = 3;
  public static final int MAS = 4;
}

