
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 33;
  public static final int DISTINTO = 27;
  public static final int LLCIERRE = 17;
  public static final int POR = 6;
  public static final int CCIERRE = 15;
  public static final int PCIERRE = 13;
  public static final int CASE = 40;
  public static final int CAP = 14;
  public static final int INT = 34;
  public static final int PUNTOCOMA = 32;
  public static final int NOT = 21;
  public static final int MENORIGUAL = 25;
  public static final int AND = 19;
  public static final int IGUAL = 8;
  public static final int LLAP = 16;
  public static final int OR = 20;
  public static final int BOOL = 35;
  public static final int DIV = 7;
  public static final int MAIN = 10;
  public static final int IF = 29;
  public static final int AMPERSAND = 9;
  public static final int MAYORIGUAL = 24;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int COMA = 11;
  public static final int MENOS = 5;
  public static final int NULL = 18;
  public static final int MENOR = 23;
  public static final int VOID = 42;
  public static final int SWITCH = 39;
  public static final int MAYOR = 22;
  public static final int ENT = 3;
  public static final int PAP = 12;
  public static final int ELSE = 30;
  public static final int PUNTO = 26;
  public static final int IDEN = 2;
  public static final int IGUALIGUAL = 28;
  public static final int WHILE = 31;
  public static final int DEFAULT = 41;
  public static final int FALSE = 37;
  public static final int MAS = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDEN",
  "ENT",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "IGUAL",
  "AMPERSAND",
  "MAIN",
  "COMA",
  "PAP",
  "PCIERRE",
  "CAP",
  "CCIERRE",
  "LLAP",
  "LLCIERRE",
  "NULL",
  "AND",
  "OR",
  "NOT",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "PUNTO",
  "DISTINTO",
  "IGUALIGUAL",
  "IF",
  "ELSE",
  "WHILE",
  "PUNTOCOMA",
  "DOSPUNTOS",
  "INT",
  "BOOL",
  "TRUE",
  "FALSE",
  "RETURN",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "VOID"
  };
}

