
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Mar 21 13:52:06 CET 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 12;
  public static final int MENOS = 6;
  public static final int IGUALIGUAL = 22;
  public static final int MENOR = 20;
  public static final int IGUAL = 9;
  public static final int IDEN = 3;
  public static final int LMAP = 17;
  public static final int CCIERRE = 14;
  public static final int POR = 7;
  public static final int CAP = 13;
  public static final int COMA = 10;
  public static final int DISTINTO = 21;
  public static final int MAYOR = 19;
  public static final int EOF = 0;
  public static final int LFILTER = 16;
  public static final int LREDUCE = 18;
  public static final int DIV = 8;
  public static final int PAP = 11;
  public static final int PRINT = 2;
  public static final int error = 1;
  public static final int ENT = 4;
  public static final int ALMOHADILLA = 15;
  public static final int MAS = 5;
}

