package asint;

//scan with {: :};
//parser code {: :};
//init with {: :};

terminal	IDEN, ENT, MAS, MENOS, POR, DIV, IGUAL, PAP, PCIERRE ;

non terminal	S, E1, E2, E3, E4, Op1, Op2, Op3 ;

// Estructura de un programa: definicion de una única expresión
S ::= IDEN IGUAL E1 ;

// Expresiones, operadores y prioridades
E1 ::= E1 Op1 E2 | E2 ;
E2 ::= E2 Op2 E3 | E3 ;
E3 ::= Op3 E3 | E4 ;
E4 ::= ENT | IDEN | PAP E1 PCIERRE ;

Op1 ::= MAS | MENOS ;
Op2 ::= POR | DIV ;
Op3 ::= MENOS ;





