
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package asint;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MENOS = 5;
  public static final int ENT = 3;
  public static final int PAP = 9;
  public static final int IDEN = 2;
  public static final int POR = 6;
  public static final int EOF = 0;
  public static final int MAS = 4;
  public static final int DIV = 7;
  public static final int IGUAL = 8;
  public static final int error = 1;
  public static final int PCIERRE = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDEN",
  "ENT",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "IGUAL",
  "PAP",
  "PCIERRE"
  };
}

