
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Apr 21 14:35:54 CEST 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 32;
  public static final int DISTINTO = 26;
  public static final int LLCIERRE = 16;
  public static final int POR = 5;
  public static final int CCIERRE = 14;
  public static final int PCIERRE = 12;
  public static final int CASE = 39;
  public static final int CAP = 13;
  public static final int INT = 33;
  public static final int PUNTOCOMA = 31;
  public static final int NOT = 20;
  public static final int MENORIGUAL = 24;
  public static final int AND = 18;
  public static final int IGUAL = 7;
  public static final int LLAP = 15;
  public static final int OR = 19;
  public static final int BOOL = 34;
  public static final int DIV = 6;
  public static final int MAIN = 9;
  public static final int IF = 28;
  public static final int AMPERSAND = 8;
  public static final int MAYORIGUAL = 23;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int TRUE = 35;
  public static final int error = 1;
  public static final int COMA = 10;
  public static final int MENOS = 4;
  public static final int NULL = 17;
  public static final int MENOR = 22;
  public static final int VOID = 41;
  public static final int SWITCH = 38;
  public static final int MAYOR = 21;
  public static final int ENT = 2;
  public static final int PAP = 11;
  public static final int ELSE = 29;
  public static final int PUNTO = 25;
  public static final int IDEN = 42;
  public static final int IGUALIGUAL = 27;
  public static final int WHILE = 30;
  public static final int DEFAULT = 40;
  public static final int FALSE = 36;
  public static final int MAS = 3;
}

